### ISSUE TITLE
[Bug]: 更新到`29927`后无法登录

### ISSUE THREAD

**Issue by latedreamdev** [LiteLoaderQQNT/LiteLoaderQQNT#1036]
### 请确保您已阅读以上注意事项，并勾选下方的确认框。

- [X] 我已经使用一个干净且无其它非必要的插件的环境测试过，问题依旧存在。
- [X] 我已经在 [Issue Tracker](https://github.com/LiteLoaderQQNT/LiteLoaderQQNT/issues) 中找过我要提出的问题，没有找到相同问题的ISSUE。
- [X] 我已知晓并同意，此处仅用于汇报主程序中存在的问题。若这个 Issue 是关于其他非程序本身问题，则我的 Issue 可能会被无条件自动关闭或/并锁定。
- [X] 我已知晓并同意，如果我不按照模板提供的指示进行填写，则我的 Issue 可能会被无条件删除。

### QQNT 版本

9.9.16-29927（64位）

### LiteLoaderQQNT 版本 （或 Commit Id）

1.2.3（745e89c）

### 运行环境

Windows

### 重现步骤

将qqnt更新到`29927`版本

### 期望的结果是什么？

登录后正常出现聊天窗口

### 实际的结果是什么？

登录后qqnt异常退出

### 日志记录

```bash
C:\Program Files\Tencent\QQNT\versions\9.9.16-29927\resources\app\application.asar\203.background.js:1


Error: invoke nt error: nodeIKernelNodeMiscService/sendLog. dlopenOrig is not defined
    at Object.logToFile (C:\Program Files\Tencent\QQNT\versions\9.9.16-29927\resources\app\application.asar\203.background.js:1:239528)
    at Object.sendLogs (C:\Program Files\Tencent\QQNT\versions\9.9.16-29927\resources\app\application.asar\background.js:1:4992)
    at Object.info (C:\Program Files\Tencent\QQNT\versions\9.9.16-29927\resources\app\application.asar\background.js:1:4518)
    at l (C:\Program Files\Tencent\QQNT\versions\9.9.16-29927\resources\app\application.asar\background.js:1:12217)
    at C:\Program Files\Tencent\QQNT\versions\9.9.16-29927\resources\app\application.asar\background.js:1:11309
    at Array.forEach (<anonymous>)
    at C:\Program Files\Tencent\QQNT\versions\9.9.16-29927\resources\app\application.asar\background.js:1:11144
    at C:\Program Files\Tencent\QQNT\versions\9.9.16-29927\resources\app\application.asar\background.js:1:79085
    at Array.forEach (<anonymous>)
    at Function.value (C:\Program Files\Tencent\QQNT\versions\9.9.16-29927\resources\app\application.asar\background.js:1:78967)

Node.js v20.14.0
```

<details>
<summary>完整日志</summary>

```bash
[LiteLoader] Found Plugin: Chii DevTools
[LiteLoader] Found Plugin: Audio Sender
[LiteLoader] Found Plugin: 修改图片概要
[LiteLoader] Found Plugin: Euphony
[LiteLoader] Found Plugin: MSpring Theme
[LiteLoader] Found Plugin: 轻量工具箱
[LiteLoader] Found Plugin: 本地查看图片和视频
[LiteLoader] Found Plugin: NapCatQQ
[LiteLoader] Found Plugin: QQNoFlash
2024-11-28 16:13:32 starting server at localhost:57027/
[NapCat] [Info] 开始初始化NapCat
Error occurred in handler for 'get-remote-win': Error: No handler registered for 'get-remote-win'
    at WebContents.<anonymous> (node:electron/js2c/browser_init:2:82968)
    at WebContents.emit (node:events:519:28)
Proxy... Event: NodeIQQNTWrapperSession/create
++++++registerSimMojoCallback+++++,
create callbak source success
Proxy... Event: NodeIKernelLoginService/get
[NapCat] Fuck LoginService Loading...
NapCat Framework App Loading...
11-28 16:13:34 [info] [QQ版本兼容性检测] 当前版本Appid未内置 通过Major获取 为了更好的性能请尝试更新NapCat
2024-11-28 16:13:34 target rtik4H: connected
[MSpring Theme] [检测] 已启用轻量工具箱
[MSpring Theme] [检测] 已启用轻量工具箱-自定义背景
[MSpring Theme] {
  '0': 'windows',
  '1': 'mspring_force_host_bubble_color',
  '2': 'mspring_lite_tool_background_enabled'
}
[MSpring Theme] [检测] 登录页面
[MSpring Theme] [设置] 开启赫蹏
C:\Program Files\Tencent\QQNT\versions\9.9.16-29927\resources\app\application.asar\203.background.js:1


Error: invoke nt error: nodeIKernelNodeMiscService/sendLog. dlopenOrig is not defined
    at Object.logToFile (C:\Program Files\Tencent\QQNT\versions\9.9.16-29927\resources\app\application.asar\203.background.js:1:239528)
    at Object.sendLogs (C:\Program Files\Tencent\QQNT\versions\9.9.16-29927\resources\app\application.asar\background.js:1:4992)
    at Object.info (C:\Program Files\Tencent\QQNT\versions\9.9.16-29927\resources\app\application.asar\background.js:1:4518)
    at l (C:\Program Files\Tencent\QQNT\versions\9.9.16-29927\resources\app\application.asar\background.js:1:12217)
    at C:\Program Files\Tencent\QQNT\versions\9.9.16-29927\resources\app\application.asar\background.js:1:11309
    at Array.forEach (<anonymous>)
    at C:\Program Files\Tencent\QQNT\versions\9.9.16-29927\resources\app\application.asar\background.js:1:11144
    at C:\Program Files\Tencent\QQNT\versions\9.9.16-29927\resources\app\application.asar\background.js:1:79085
    at Array.forEach (<anonymous>)
    at Function.value (C:\Program Files\Tencent\QQNT\versions\9.9.16-29927\resources\app\application.asar\background.js:1:78967)

Node.js v20.14.0
```
</details>

### 补充说明（可选）

~~看错误日志感觉像qqnt内部问题~~
总之只能靠@mo-jinran大佬火速适配`29927`版本了(

**Comment by BachWV** [comment]
我可以使用29927正常登录，只不过几个小时后会被踢下线，liteloader版本是1.2.3

**Comment by latedreamdev** [comment]
我的我的 我忘记升级napcat了(

**Comment by xiaohanbao263** [comment]
> 我可以使用29927正常登录，只不过几个小时后会被踢下线，liteloader版本是1.2.3
最新版qqnt貌似加了新检测 下线几次之后你qq号就封了

**Comment by latedreamdev** [comment]
啊? 还带封号的 火速降级(

**Comment by xiaohanbao263** [comment]
> 啊? 还带封号的 火速降级(

是的 我qq下线了几次就封了

**Comment by Linearpast** [comment]
降低版本之后一天没被踢了，再看看
