### ISSUE TITLE
[Bug]: protocol.handle is not a function

### ISSUE THREAD

**Issue by littleaya** [LiteLoaderQQNT/LiteLoaderQQNT#279]
### 请确保您已阅读以上注意事项，并勾选下方的确认框。

- [X] 我已经使用一个干净且无其它非必要的插件的环境测试过，问题依旧存在。
- [X] 我已经在 [Issue Tracker](https://github.com/LiteLoaderQQNT/LiteLoaderQQNT/issues) 中找过我要提出的问题，没有找到相同问题的ISSUE。
- [X] 我已知晓并同意，此处仅用于汇报主程序中存在的问题。若这个 Issue 是关于其他非程序本身问题，则我的 Issue 可能会被无条件自动关闭或/并锁定。
- [X] 我已知晓并同意，如果我不按照模板提供的指示进行填写，则我的 Issue 可能会被无条件删除。

### QQNT 版本

qq for linux 3.1.2

### LiteLoaderQQNT 版本 （或 Commit Id）

1.1.1

### 运行环境

Linux

### 重现步骤

用LiteLoaderQQNT_Install安装了LiteLoaderQQNT，在qq启动时发生错误，报错TypeError: protocol.handle is not a function

### 期望的结果是什么？

正确启动

### 实际的结果是什么？

初始化或者启动过程中发生错误

### 日志记录

[LiteLoader][0m Plugins directory created successfully!
 [ERROR] [Main] TypeError: protocol.handle is not a function
(node:43) UnhandledPromiseRejectionWarning: TypeError: protocol.handle is not a function
at protocolRegister (/opt/LiteLoader/src/main.js:71:18)
at Object.proxyBrowserWindowConstruct [as construct] (/opt/LiteLoader/src/main.js:103:5)
at S.createWin (evalmachine.<anonymous>:1:951586)
at R.createWindow (evalmachine.<anonymous>:1:954103)
at R.getWindow (evalmachine.<anonymous>:1:953511)
at K.createWindow (evalmachine.<anonymous>:1:957084)
at _s.initWindow (evalmachine.<anonymous>:1:983486)
at new e (evalmachine.<anonymous>:1:980365)
at new _s (evalmachine.<anonymous>:1:572931)
at Object.getWindow (evalmachine.<anonymous>:1:955551)
(Use `qq --trace-warnings ...` to show where the warning was created)
(node:43) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)

**Comment by mo-jinran** [comment]
目前使用新版liteloader与qqnt是否还存在此问题？

**Comment by mo-jinran** [comment]
更新1.2.0版本
