### ISSUE TITLE
[Bug]: 手动复制preload.js文件后，启动时仍报错权限问题

### ISSUE THREAD

**Issue by clague** [LiteLoaderQQNT/LiteLoaderQQNT#349]
### 请确保您已阅读以上注意事项，并勾选下方的确认框。

- [X] 我已经使用一个干净且无其它非必要的插件的环境测试过，问题依旧存在。
- [X] 我已经在 [Issue Tracker](https://github.com/LiteLoaderQQNT/LiteLoaderQQNT/issues) 中找过我要提出的问题，没有找到相同问题的ISSUE。
- [X] 我已知晓并同意，此处仅用于汇报主程序中存在的问题。若这个 Issue 是关于其他非程序本身问题，则我的 Issue 可能会被无条件自动关闭或/并锁定。
- [X] 我已知晓并同意，如果我不按照模板提供的指示进行填写，则我的 Issue 可能会被无条件删除。

### QQNT 版本

3.2.10-25765

### LiteLoaderQQNT 版本 （或 Commit Id）

0194c17

### 运行环境

Linux

### 重现步骤

编辑`resources\app\app_launcher\index.js`，修改QQ目录权限，启动QQ。或者手动复制需要的文件，仍报相同错误。

### 期望的结果是什么？

正常启动

### 实际的结果是什么？

报错并卡住，没有显示窗口

### 日志记录

```
version_config_filename :/home/clague/.config/QQ/versions/config.json
app_package_filename :/opt/QQ/electron --no-proxy-server --enable-wayland-ime --ozone-platform-hint=wayland --ignore-gpu-blocklist --disable-gpu /opt/QQ/resources/resources/app/package.json
config_build_id :
config_base_version :3.2.10-25765
config_current_version :
app_build_version :
version_config_filename :/home/clague/.config/QQ/versions/config.json
version_config_filename :/home/clague/.config/QQ/versions/config.json
app_package_filename :/opt/QQ/resources/app/package.json
app_package_filename :/opt/QQ/resources/app/package.json
config_build_id :
config_build_id :
config_base_version :3.2.10-25765
config_base_version :3.2.10-25765
config_current_version :
config_current_version :
app_build_version :25765
app_build_version :25765
[preload] succeeded. /opt/QQ/resources/app/major.node
[preload] succeeded. /opt/QQ/resources/app/major.node
[LiteLoader] Use LITELOADERQQNT_PROFILE environment variables: /home/clague/.config/QQ/LiteLoaderQQNT
[LiteLoader] Start finding all plugins.
[LiteLoader] Found 0 plugins, no plugin to be loaded.
(node:334492) UnhandledPromiseRejectionWarning: Error: EROFS: read-only file system, copyfile '/opt/LiteLoader/src/preload.js' -> '/opt/QQ/resources/app/application/../application/preload_login.js'
    at Object.copyFileSync (node:fs:3013:11)
    at Object.func [as copyFileSync] (node:electron/js2c/node_init:2:3119)
    at processPreloadPath (/opt/LiteLoader/src/main.js:30:12)
    at Object.proxyBrowserWindowConstruct [as construct] (/opt/LiteLoader/src/main.js:44:26)
    at p (/opt/QQ/resources/app/application/background.js)
    at App.c (/opt/QQ/resources/app/application/background.js)
    at App.emit (node:events:519:28)
(Use `electron --trace-warnings ...` to show where the warning was created)
(node:334492) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
```

### 补充说明（可选）

手动复制文件后，注释掉`src/main.js`的第 30 行
```
fs.copyFileSync(liteloader_preload_path, new_preload_path);
```
能正常启动。

**Comment by mo-jinran** [comment]
```
UnhandledPromiseRejectionWarning: Error: EROFS: read-only file system, copyfile '/opt/LiteLoader/src/preload.js' -> '/opt/QQ/resources/app/application/../application/preload_login.js'
```
报错依旧是权限问题，确保为可写？我在Linux下无法复现

**Comment by clague** [comment]
发现了其实是因为`bwrap`只绑定了读权限，不过希望能改成当检测文件相同时不进行复制操作，这样可以不给写权限手动复制。

**Comment by LynxCatTheThird** [comment]
我也遇到了此问题，在 `start_mac_fix.sh`中做出如下修补后即可启动。但只能出现扫码登录，登陆后仍然不能显示主界面。@clague 请问您是如何修复的？

```diff
127c127
<     --bind /opt /opt \
---
>     --ro-bind /opt /opt \
```

日志：https://netcut.cn/p/9a921b9307910e79

**Comment by mo-jinran** [comment]
最新的commit已兼容
