### ISSUE TITLE
[Bug]:  启动时发生错误 Invalid package

### ISSUE THREAD

**Issue by SakuraPuare** [LiteLoaderQQNT/LiteLoaderQQNT#352]
### 请确保您已阅读以上注意事项，并勾选下方的确认框。

- [X] 我已经使用一个干净且无其它非必要的插件的环境测试过，问题依旧存在。
- [X] 我已经在 [Issue Tracker](https://github.com/LiteLoaderQQNT/LiteLoaderQQNT/issues) 中找过我要提出的问题，没有找到相同问题的ISSUE。
- [X] 我已知晓并同意，此处仅用于汇报主程序中存在的问题。若这个 Issue 是关于其他非程序本身问题，则我的 Issue 可能会被无条件自动关闭或/并锁定。
- [X] 我已知晓并同意，如果我不按照模板提供的指示进行填写，则我的 Issue 可能会被无条件删除。

### QQNT 版本

3.2.10_25765-2

### LiteLoaderQQNT 版本 （或 Commit Id）

2c3a826

### 运行环境

Linux

### 重现步骤

 在 [2c3a826](https://github.com/LiteLoaderQQNT/LiteLoaderQQNT/commit/2c3a826a0afdb5f58f86a80f6037c58918a5acf7)
```
# 回退到 2c3a826
git reset  --hard 2c3a826

#  启动QQ
linuxqq
```

### 期望的结果是什么？

正常启动

### 实际的结果是什么？

无法显示聊天主页面

```
❯ linuxqq
User flags: --enable-features=UseOzonePlatform --ozone-platform=wayland --enable-wayland-ime
version_config_filename :/home/sakurapuare/.config/QQ/versions/config.json
app_package_filename :/opt/QQ/resources/app/package.json
config_build_id :25765
config_base_version :3.2.10-25765
config_current_version :3.2.10-25765
app_build_version :25765
version_config_filename :/home/sakurapuare/.config/QQ/versions/config.json
app_package_filename :/opt/QQ/resources/app/package.json
config_build_id :25765
config_base_version :3.2.10-25765
config_current_version :3.2.10-25765
app_build_version :25765
version_config_filename :/home/sakurapuare/.config/QQ/versions/config.json
app_package_filename :/opt/QQ/resources/app/package.json
[preload] succeeded. /opt/QQ/resources/app/major.node
config_build_id :25765
config_base_version :3.2.10-25765
config_current_version :3.2.10-25765
app_build_version :25765
[preload] succeeded. /opt/QQ/resources/app/major.node
[LiteLoader] Start finding all plugins.
[LiteLoader] Found 0 plugins, no plugin to be loaded.
A JavaScript error occurred in the main process
Uncaught Exception:
Error: Invalid package /opt/QQ/resources/app/application.asar/
    at createError (node:electron/js2c/node_init:2:2858)
    at t.readdirSync (node:electron/js2c/node_init:2:15357)
    at Object.<anonymous> (/home/sakurapuare/Project/LiteLoaderQQNT/src/init.js:23:37)
    at Module._compile (node:internal/modules/cjs/loader:1373:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1432:10)
    at Module.load (node:internal/modules/cjs/loader:1215:32)
    at Module._load (node:internal/modules/cjs/loader:1031:12)
    at f._load (node:electron/js2c/node_init:2:18640)
    at Module.require (node:internal/modules/cjs/loader:1240:19)
    at require (node:internal/modules/helpers:179:18)
Gtk-Message: 01:01:31.683: Failed to load module "appmenu-gtk-module"
```

### 日志记录

```
Error: Invalid package /opt/QQ/resources/app/application.asar/
    at createError (node:electron/js2c/node_init:2:2858)
    at t.readdirSync (node:electron/js2c/node_init:2:15357)
    at Object.<anonymous> (/home/sakurapuare/Project/LiteLoaderQQNT/src/init.js:23:37)
    at Module._compile (node:internal/modules/cjs/loader:1373:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1432:10)
    at Module.load (node:internal/modules/cjs/loader:1215:32)
    at Module._load (node:internal/modules/cjs/loader:1031:12)
    at f._load (node:electron/js2c/node_init:2:18640)
    at Module.require (node:internal/modules/cjs/loader:1240:19)
    at require (node:internal/modules/helpers:179:18)
```

### 补充说明（可选）

```
❯ fastfetch
                  -`                     sakurapuare@ShuYingJiYu
                 .o+`                    -----------------------
                `ooo/                    OS: Arch Linux x86_64
               `+oooo:                   Host: ASUS TUF Gaming F15 FX507ZM_FX507ZM (1.0)
              `+oooooo:                  Kernel: Linux 6.10.0-arch1-2
              -+oooooo+:                 Uptime: 33 mins
            `/:-:++oooo+:                Packages: 2966 (pacman)
           `/++++/+++++++:               Shell: zsh 5.9
          `/++++++++++++++:              Display (CMN1540): 2560x1440 @ 165 Hz (as 1706x960) in 16″ [Built]
         `/+++ooooooooooooo/`            DE: KDE Plasma 6.1.3
        ./ooosssso++osssssso+`           WM: KWin (Wayland)
       .oossssso-````/ossssss+`          WM Theme: Breeze 微风
      -osssssso.      :ssssssso.         Theme: Breeze (MaterialYouLight) [Qt], Breeze [GTK2/3]
     :osssssss/        osssso+++.        Icons: Tela-pink-light [Qt], Tela-pink-light [GTK2/3/4]
    /ossssssss/        +ssssooo/-        Font: 思源黑体 (10pt) [Qt], 思源黑体 (10pt) [GTK2/3/4]
  `/ossssso+/:-        -:/+osssso+-      Cursor: Breeze_Light (24px)
 `+sso+:-`                 `.-/+oso:     Terminal: konsole 24.5.2
`++:.                           `-/+/    Terminal Font: JetBrainsMono NF (12pt, Regular)
.`                                 `/    CPU: 12th Gen Intel(R) Core(TM) i7-12700H (20) @ 4.70 GHz
                                         GPU 1: NVIDIA GeForce RTX 3060 Mobile / Max-Q [Discrete]
                                         GPU 2: Intel Iris Xe Graphics @ 1.40 GHz [Integrated]
                                         Memory: 8.19 GiB / 38.80 GiB (21%)

```

在 [0194c17](https://github.com/LiteLoaderQQNT/LiteLoaderQQNT/commit/0194c17)
 
能正常启动
``` 
❯ git reset --hard 0194c17
HEAD 现在位于 0194c17 反正先把loader相关的分离出来，以后再优化吧
❯ linuxqq
User flags: --enable-features=UseOzonePlatform --ozone-platform=wayland --enable-wayland-ime
version_config_filename :/home/sakurapuare/.config/QQ/versions/config.json
app_package_filename :/opt/QQ/resources/app/package.json
config_build_id :25765
config_base_version :3.2.10-25765
config_current_version :3.2.10-25765
app_build_version :25765
version_config_filename :/home/sakurapuare/.config/QQ/versions/config.json
app_package_filename :/opt/QQ/resources/app/package.json
config_build_id :25765
config_base_version :3.2.10-25765
config_current_version :3.2.10-25765
app_build_version :25765
[preload] succeeded. /opt/QQ/resources/app/major.node
version_config_filename :/home/sakurapuare/.config/QQ/versions/config.json
app_package_filename :/opt/QQ/resources/app/package.json
config_build_id :25765
config_base_version :3.2.10-25765
config_current_version :3.2.10-25765
app_build_version :25765
[preload] succeeded. /opt/QQ/resources/app/major.node
[LiteLoader] Start finding all plugins.
[LiteLoader] Found 0 plugins, no plugin to be loaded.
Gtk-Message: 01:05:19.214: Failed to load module "appmenu-gtk-module"
[110496:0726/010519.250753:ERROR:check.cc(376)] Check failed: false. NOTREACHED log messages are omitted in official builds. Sorry!
[110496:0726/010519.257057:ERROR:check.cc(376)] Check failed: false. NOTREACHED log messages are omitted in official builds. Sorry!
Error occurred in handler for 'get-remote-win': Error: No handler registered for 'get-remote-win'
    at WebContents.<anonymous> (node:electron/js2c/browser_init:2:82968)
    at WebContents.emit (node:events:519:28)

(qq:110441): VIPS-WARNING **: 01:05:19.387: unable to load "/usr/lib/vips-modules-8.15/vips-openslide.so" -- libopenslide.so.1: 无法打开共享目标文件: 没有那个文件或目录
linux-bugly: init bugly ...
InitBuglyManager
SetLogger
fatalSetup
GetDllPath: 49
pub_key_path: /opt/QQ/resources/app/application//../pub.key
[BuglyManager.cpp][InitBuglyManager][212]InitBuglyManager path: /home/sakurapuare/.config/QQ/crash_files/
BuglyManager/opt/QQ/resources/app/application//../pub.key
[BuglyService.cpp][registBugly][589]set signal stack
[BuglyService.cpp][registSignalHandler][520]regist native handler
registBugly/opt/QQ/resources/app/application//../pub.key
[BuglyService.cpp][setParam][618]setParam, key:appVersion, value:3.2.10-25765..
setParam/opt/QQ/resources/app/application//../pub.key
StartWithOptions s/opt/QQ/resources/app/application//../pub.key
StartWithOptions e/opt/QQ/resources/app/application//../pub.key
PostDelayedTask s/opt/QQ/resources/app/application//../pub.key
PostDelayedTask e/opt/QQ/resources/app/application//../pub.key
linux-bugly: init bugly done.
[110737:0726/010522.903590:ERROR:check.cc(376)] Check failed: false. NOTREACHED log messages are omitted in official builds. Sorry!
[110737:0726/010522.913197:ERROR:check.cc(376)] Check failed: false. NOTREACHED log messages are omitted in official builds. Sorry!
[110857:0726/010524.490538:ERROR:check.cc(376)] Check failed: false. NOTREACHED log messages are omitted in official builds. Sorry!
[110857:0726/010524.499808:ERROR:check.cc(376)] Check failed: false. NOTREACHED log messages are omitted in official builds. Sorry!
01:05:26.653 › [hot update] 

------------ app 启动分界线 ------------

01:05:26.660 › [hot update] hotUpdateApi checkHasMultipleQQ:  false
01:05:26.660 › [hot update] hotUpdateApi clearOldVersions start
01:05:26.661 › [hot update] {
  "baseVersion": "3.2.10-25765",
  "curVersion": "3.2.10-25765",
  "prevVersion": "",
  "onErrorVersions": [],
  "buildId": "25765",
  "unzipRetryCount": 0
}
01:05:26.661 › [hot update] start update check
01:05:26.762 › [hot update] ----- startUpdate -----
01:05:26.766 › [hot update] hotUpdateApi checkHasMultipleQQ:  false
01:05:26.767 › [hot update] hotUpdateApi start check  3.2.9-24402  IsOnErrorVersion
01:05:26.767 › [hot update] hotUpdateApi checkIsOnErrorVersion result: false
01:05:26.768 › [hot update] [startUpdate] 无需更新
^C
```

**Comment by LynxCatTheThird** [comment]
https://github.com/LiteLoaderQQNT/LiteLoaderQQNT/issues/349#issuecomment-2249538101

**Comment by mo-jinran** [comment]
最新的commit已兼容
